# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_repos:
- branch: master
  name: pulp_file
black: false
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: true
issue_tracker: redmine
plugin_app_label: certguard
plugin_camel: PulpCertguard
plugin_camel_short: Certguard
plugin_caps: PULP-CERTGUARD
plugin_caps_short: CERTGUARD
plugin_dash: pulp-certguard
plugin_dash_short: certguard
plugin_default_branch: master
plugin_name: pulp-certguard
plugin_snake: pulp_certguard
publish_docs_to_pulpprojectdotorg: true
pulp_settings: null
pulpcore_branch: '3.12'
pulpcore_pip_version_specifier: ~=3.12.0
pulpprojectdotorg_key_id: null
pydocstyle: true
pypi_username: pulp
redmine_project: certguard
stable_branch: null
test_bindings: false
test_cli: false
test_fips_nightly: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: false
travis_addtl_services: []
travis_notifications: null
update_redmine: false
upgrade_range: []

