# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins:
- { name: pulp_file, branch: master }
black: false
check_commit_message: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: true
plugin_app_label: certguard
plugin_camel: PulpCertguard
plugin_camel_short: Certguard
plugin_caps: PULP-CERTGUARD
plugin_caps_short: CERTGUARD
plugin_dash: pulp-certguard
plugin_dash_short: certguard
plugin_name: pulp-certguard
plugin_snake: pulp_certguard
pulp_settings: null
pulpcore_branch: master
pydocstyle: true
pypi_username: pulp
stable_branch: null
test_bindings: true
test_performance: false
travis_notifications: null

